# Generated by Django 5.0.1 on 2024-02-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diettracker', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('max_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('max_fat', models.PositiveIntegerField(blank=True, null=True)),
                ('max_protein', models.PositiveIntegerField(blank=True, null=True)),
                ('max_carbohydrates', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='diettracker.food'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('calories', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('carbohydrates', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diettracker.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diettracker.diet'),
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diettracker.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
