# Generated by Django 5.0.2 on 2024-02-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diettracker', '0003_meal_delete_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='name',
            field=models.CharField(default='not available', max_length=100),
        ),
    ]
